name: Flet Split APK Build

on:
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1733015761
  BUILD_VERSION: 10.0.0
  PYTHON_VERSION: 3.12.5
  FLUTTER_VERSION: 3.24.3
  # ANDROID_PLATFORM_TARGET: 'arm64' # arm, arm64, x64, x86
  # BUILD_ARCH: 'armeabi-v7a,arm64-v8a' # armeabi-v7a, arm64-v8a, x64, x86
  
  PROJECT: ynet
  COMPANY_NAME: omamkaz
  ORG_NAME: com.omamkaz
  PRODUCT: ynet
  DESCRIPTION: Yemen Net Internet Services

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove cache files
      run: |
        rm -rf .git
        rm -rf .github
        rm .gitignore

    - name: Patch for APK build
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          curl \
          git \
          unzip \
          xz-utils \
          zip \
          libglu1-mesa \
          ninja-build \
          libgtk-3-dev \
          build-essential \
          python3-dev \
          libc6:amd64 libstdc++6:amd64 \
          libbz2-1.0:amd64

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        # architecture: 'x64'

    - name: Setup Python Environment and Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install -r requirements.txt

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'
        #architecture: 'aarch64'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flet Build APK
      run: |
        flutter doctor
        flutter config --no-analytics
        flet build apk \
        --verbose \
        --split-per-abi \
        --android-adaptive-icon-background="#ffffff" \
        --include-packages flet_lottie \
        --build-number="$BUILD_NUMBER" \
        --build-version="$BUILD_VERSION" \
        --company="$COMPANY_NAME" \
        --org="$ORG_NAME" \
        --product="$PRODUCT" \
        --description="$DESCRIPTION" \
        --project="$PROJECT" \
        --flutter-build-args=--release \
        --flutter-build-args=--target-platform \
        --flutter-build-args=android-arm64

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        path: build/apk
        name: apk-build-artifact
        if-no-files-found: warn
        overwrite: false
